title: SecureX orchestration
description: >-
 Documentation and workflow information for Cisco XDR.

baseurl: "/sxo-05-xdr-wsg"
url: "https://sokovalc.github.io"

logo: "/assets/images/logo.png"

remote_theme: pmarsceill/just-the-docs

site.favicon: "/favicon.ico"

aux_links:
  "GitHub Repository":
    - "https://github.com/sokovalc/sxo-05-xdr-wsg"

back_to_top: true
back_to_top_text: "Back to top"

color_scheme: cisco

footer_content: "Copyright &copy; 2024 Cisco Systems, Inc. <a href=\"https://github.com/CiscoSecurity/sxo-05-security-workflows/blob/Main/LICENSE.md\">View License</a>"

plugins:
  - jekyll-redirect-from

gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/sokovalc/sxo-05-xdr-wsgs"
gh_edit_branch: "Main"
gh_edit_source: docs
gh_edit_view_mode: "tree"
